require "stringio"

module WARB; end
module WARB::Value; end

require "warb/version"
require "warb/errors"
require "warb/module_io"
require "warb/value/primitive"
require "warb/value/integerize"
require "warb/value/i32"
require "warb/value/i64"
require "warb/value/floatize"
require "warb/value/f32"
require "warb/value/f64"
require "warb/value/class_detector"
require "warb/function_type"
require "warb/structured/block"
require "warb/structured/if_else"
require "warb/structured/loop"
require "warb/structured/indexed_blocks"
require "warb/frame"
require "warb/instructions"
require "warb/stack"
require "warb/function"
require "warb/limit"
require "warb/constant_expr"
require "warb/custom"
require "warb/memory"
require "warb/table"
require "warb/global"
require "warb/contextual_function"
require "warb/module"
