require "stringio"

module WasmMachine; end
module WasmMachine::ControlFlow; end

require "wasm_machine/version"
require "wasm_machine/errors"
require "wasm_machine/binary_io"
require "wasm_machine/value_type"
require "wasm_machine/function_type"
require "wasm_machine/control_flow/structured_instruction"
require "wasm_machine/control_flow/if_else"
require "wasm_machine/control_flow/loop"
require "wasm_machine/control_flow/block"
require "wasm_machine/frame"
require "wasm_machine/instructions"
require "wasm_machine/invocation"
require "wasm_machine/label"
require "wasm_machine/stack"
require "wasm_machine/value"
require "wasm_machine/function"
require "wasm_machine/limit"
require "wasm_machine/constant_expr"
require "wasm_machine/custom"
require "wasm_machine/memory"
require "wasm_machine/global"
require "wasm_machine/module"
